/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CacheableIcoImg: typeof import('./src/components/util/CacheableIcoImg.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    IcoTableDialog: typeof import('./src/components/dialog/IcoTableDialog.vue')['default']
    InputDialog: typeof import('./src/components/dialog/InputDialog.vue')['default']
    InputUrlDialog: typeof import('./src/components/dialog/InputUrlDialog.vue')['default']
    ItemOperateDialog: typeof import('./src/components/dialog/ItemOperateDialog.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    MaterialInput: typeof import('./src/components/util/MaterialInput.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchEngineTableDialog: typeof import('./src/components/dialog/SearchEngineTableDialog.vue')['default']
    WebItem: typeof import('./src/components/WebItem.vue')['default']
  }
}
